name: Build and Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: |
        npm run build
        cp package.json dist/server/

    - name: Deploy to VPS via SCP
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22008
        source: "dist/*"
        target: "/var/www/tpsvg2025/"
        strip_components: 1
        rm: false
        overwrite: true
        debug: true

    - name: Install production dependencies on VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22008
        script: |
          cd /var/www/tpsvg2025/server
          npm ci
          npm install astro send server-destroy
          PORT=8087 pm2 restart tpsvg2025 || PORT=8087 pm2 start entry.mjs --name tpsvg2025
